version: '3'

db:
    image: postgres
    environment:
      POSTGRES_USER: oxynger
      POSTGRES_PASSWORD: 12345
    volumes:
      - /var/constainers/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432